### ISSUE TITLE
Пример

### ISSUE THREAD

**Issue by altpoint** [goaop/goaop-laravel-bridge#1]
Приветствую. А примера не будет никакого кроме как с логером?
Можно ли, например, как-то "врезаться" в выволнение методов у класса UploadedFile ?

**Comment by lisachenko** [comment]
Да, если нужно врезаться в выполнение методов `UploadedFile` - просто добавьте путь до `framework/src/Illuminate/Http` в массив `includePaths`. После этого можно будет перехватывать методы внутри файлов фреймворка.
