### ISSUE TITLE
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by benadavid** [goaop/goaop-laravel-bridge#12]
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
                                                                               
  [InvalidArgumentException]                                                   
  Cache directory /home/travis/build/g-harel/SOEN343/storage/aspect is not wr  
  itable                                                                       
                                                                               
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

How do you fix this error?
thanks

**Comment by qrazi** [comment]
This looks like a permission problem. Go! AOP would normally write files to the filesystem, but it does not have the right to do so. In this case it means the user under which the `php artisan` command is run, does not have the right to write in the storage directory. If the website is browsable in a browser, then permissions are setup properly for the webserver user.

I usually add my user to the `www-data` group, and if necessary add write or execute right to the group (`chmod -R g+wx ./storage`), but I'm honestly not sure if that's best practice.

**Comment by SerafimArts** [comment]
In addition, I recommend adding the same permissions to the `./bootstrap` directory. It also contains an autogenerated code (a list of services).

**Comment by SerafimArts** [comment]
@benadavid is necessary changes of the permissions to the directory with the cache solved your problem?

**Comment by SerafimArts** [comment]
I close this issue, because for a long time there was no answer. And most likely the problem was solved. If it occurs again, simply create a new.

**Comment by lisachenko** [comment]
👍
