### ISSUE TITLE
'\self' is an invalid class name

### ISSUE THREAD

**Issue by tpapic** [goaop/goaop-laravel-bridge#15]
I was following your init tutorial with logging but I always get this error.

` '\self' is an invalid class name {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): '\\self' is an invalid class name at npp/project/api/storage/app/aspect/_proxies/app/User.php/App/User.php:1055)
`
Method which has this error 

```
/**
     * Create a new pivot model instance.
     *
     * @param  \Illuminate\Database\Eloquent\Model  $parent
     * @param  array  $attributes
     * @param  string  $table
     * @param  bool  $exists
     * @param  string|null  $using
     * @return \Illuminate\Database\Eloquent\Relations\Pivot
     */
    public function newPivot(\self $parent, array $attributes, $table, $exists, $using = NULL)
    {
        return self::$__joinPoints['method:newPivot']->__invoke($this, \array_slice([$parent, $attributes, $table, $exists, $using], 0, \func_num_args()));
    }
```

PHP-version: 7.1.23
Laravel version: 5.5

**Comment by SerafimArts** [comment]
@tpapic can you please rediscover this issue here https://github.com/goaop/framework/issues ? This issue applies to any code where typehint `self` is used.

@lisachenko a brief example that reproduces the error:

```php
class Example
{
    public function example(self $arg): self
    {
        return $arg;
    }
}
```

Aspect:
```
@Before("execution(public Example->example(*))")
```

**Comment by SerafimArts** [comment]
I close this issue in order not to duplicate it.

**Comment by lisachenko** [comment]
Please, update `goaop/framework` to >=2.3.0 to have this issue fixed.
