### ISSUE TITLE
 Cache directory is not writeable

### ISSUE THREAD

**Issue by tatocaster** [goaop/goaop-laravel-bridge#2]
`'cacheDir' => storage_path('app/aspect')`

 Cache directory is not writeable

thats why , I cannot publish from artisan command. please fix to `storage_path('app/aspect')`

**Comment by lisachenko** [comment]
Hi, could you please recheck your issue?

Looks like something is wrong in your issue, because you asking me to change `storage_path('app/aspect')` to the same value: `storage_path('app/aspect')`

**Comment by tatocaster** [comment]
Yeah sorry, I have mistake in path. change to  `storage_path('aspect')` . because of this I had problems to uninstall package also. I had to manually `chmod + w` whole directory for write access and then manually remove. All other folders under `storage/` folder are well, but `app/` is a problem. 

 I think for all cases its better to move cache in `storage/` because all other packages also use this directory.

**Comment by lisachenko** [comment]
I think that this option can be easily configured for your concrete instance after installing assets to the app via

```
./artisan vendor:publish --provider="Go\Laravel\GoAopBridge\GoAopServiceProvider"
```

Then you will be able to change configuration value in the `./config/go_aop.php` file to the `storage_path('aspect')`
