### ISSUE TITLE
Files get created without permission

### ISSUE THREAD

**Issue by i3anaan** [goaop/goaop-laravel-bridge#7]
Heyho,

Found this framework, got really excited, but now running into problems. After fighting with the initial setup we are now running in an issue where all the files (and directories) created for Go! Aop (in storage/app/aspect) are without permissions. Umask is ignored and I have no clue how else to solve this.

We are using Laravel 5.4 inside a Ubuntu 16.04 docker container.

Error log:
```
omscore_1                   | Bootstrapping...
omscore_1                   | Loading composer repositories with package information
omscore_1                   | Installing dependencies (including require-dev) from lock file
omscore_1                   | Nothing to install or update
omscore_1                   | Generating autoload files
omscore_1                   | > Illuminate\Foundation\ComposerScripts::postInstall
omscore_1                   | > php artisan optimize
omscore_1                   | PHP Fatal error:  Uncaught InvalidArgumentException: The directory "/var/www/storage/app/aspect/_annotations" is not writable. Both, the webserver and the console user need access. You can manage access rights for multiple users with "chmod +a". If your system does not support this, check out the acl package. in /var/www/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php:208
omscore_1                   | Stack trace:
omscore_1                   | #0 /var/www/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php(180): Doctrine\Common\Annotations\FileCacheReader->saveCacheFile('/var/www/storag...', Array)
omscore_1                   | #1 /var/www/vendor/goaop/framework/src/Core/AspectLoader.php(213): Doctrine\Common\Annotations\FileCacheReader->getMethodAnnotations(Object(ReflectionMethod))
omscore_1                   | #2 /var/www/vendor/goaop/framework/src/Core/AspectLoader.php(181): Go\Core\AspectLoader->getAnnotations(Object(ReflectionMethod))
omscore_1                   | #3 /var/www/vendor/goaop/framework/src/Core/AspectLoader.php(101): Go\Core\AspectLoader->loadFrom(Object(App\Aspect\PermissionAspect), Object(Refle in /var/www/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php on line 208
omscore_1                   | PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
omscore_1                   | Stack trace:
omscore_1                   | #0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('App\\Exceptions\\...')
omscore_1                   | #1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('App\\Exceptions\\...')
omscore_1                   | #2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array)
omscore_1                   | #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->makeWith('App\\Exceptions\\...', Array)
omscore_1                   | #4 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(248): Illuminate\Foundation\Application->makeWith('App\\Exceptions\\...', Array)
omscore_1                   | #5 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Illuminate\Container\Containe in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
omscore_1                   | Script php artisan optimize handling the post-install-cmd event returned with error code 255
omscore_1                   | Error at composer install
dockerdev_omscore_1 exited with code 10
```

Folder:
```
root@c032b249d4c1:/var/www/storage/app/aspect# ls -la
total 12
drwxrwxrwx 3 laradock laradock 4096 Jul 11 15:48 .
drwxrwxr-x 4 laradock laradock 4096 Jul 11 15:48 ..
d--------- 2 laradock laradock 4096 Jul 11 15:48 _annotations
```

Having made the folder writable using `chmod a+rwx _annotations`
```
Bootstrapping...
omscore_1                   | Loading composer repositories with package information
omscore_1                   | Installing dependencies (including require-dev) from lock file
omscore_1                   | Nothing to install or update
omscore_1                   | Generating autoload files
omscore_1                   | > Illuminate\Foundation\ComposerScripts::postInstall
omscore_1                   | > php artisan optimize
omscore_1                   | PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/storage/app/aspect/_annotations/5965ee6532f7c4.45340361Io0vUn): failed to open stream: Permission denied in /var/www/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php:219
omscore_1                   | Stack trace:
omscore_1                   | #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/vendor...', 219, Array)
omscore_1                   | #1 /var/www/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php(219): file_put_contents('/var/www/storag...', '<?php return un...')
omscore_1                   | #2 /var/www/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php(180): Doctrine\Common\Annotations\FileCacheReader->saveCacheFile('/var/www/storag...', Array)
omscore_1                   | #3 /var/www/vendor/goaop/framework/src/Core/AspectLoader.php(213): Doctrine\Common\Annotations\FileCacheReader->getMethodAnnotations(Object(ReflectionMethod))
omscore_1                   | #4 /var/www/vendor/goaop/framework/src/Core/AspectLoader.php(181): Go\Core\AspectLoader->getAnnotations(Obje in /var/www/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php on line 219
omscore_1                   | PHP Fatal error:  Uncaught ReflectionException: Class App\Exceptions\Handler does not exist in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
omscore_1                   | Stack trace:
omscore_1                   | #0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('App\\Exceptions\\...')
omscore_1                   | #1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('App\\Exceptions\\...')
omscore_1                   | #2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\Container->resolve('App\\Exceptions\\...', Array)
omscore_1                   | #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(709): Illuminate\Container\Container->makeWith('App\\Exceptions\\...', Array)
omscore_1                   | #4 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(248): Illuminate\Foundation\Application->makeWith('App\\Exceptions\\...', Array)
omscore_1                   | #5 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Illuminate\Container\Containe in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
omscore_1                   | Script php artisan optimize handling the post-install-cmd event returned with error code 255
omscore_1                   | Error at composer install
```

Giving the files permissions does not help, as each time new files are created.
```
root@9be6c0518d2e:/var/www/storage/app/aspect/_annotations# ls -la
total 8
drwxrwxrwx 2 laradock laradock 4096 Jul 12 09:42 .
drwxrwxrwx 3 laradock laradock 4096 Jul 11 15:48 ..
-rwxrwxrwx 1 laradock laradock    0 Jul 12 09:39 5965ee65320da0.33929314v0ioEk
-rwxrwxrwx 1 laradock laradock    0 Jul 12 09:39 5965ee6532e256.08893502imaqhm
-rwxrwxrwx 1 laradock laradock    0 Jul 12 09:39 5965ee6532f7c4.45340361Io0vUn
---------- 1 laradock laradock    0 Jul 12 09:42 5965eef335d5e2.45033206EGDZEf
---------- 1 laradock laradock    0 Jul 12 09:42 5965eef33685e2.88233170UJ2Ezi
---------- 1 laradock laradock    0 Jul 12 09:42 5965eef3369da5.02796523JJLoul
```

Full code from our project can be found here: https://github.com/AEGEE/oms-neo-core/tree/perm-aop
We have not yet run into any issues like this with any other part of the system.

**Comment by i3anaan** [comment]
Experimenting with changing `'cacheFileMode' => null,` to something else is doing some things, yet so far I have not yet understood the logic of this and I am pretty much putting random bitmask in there.

**Comment by i3anaan** [comment]
I continued trying to fix it, yet decided to leave it be for now. The end conclusion is that something somewhere is creating wrong permissions, applying a wrong umask, misusing the cacheFileMode, or something else. Through experimenting, I ended up with setting weird things, such as the sticky bit (t) and a door (??) (D). I think in the end it is better for someone to look at this who worked on it before and who should now better what is supposed to happen and where it differs.

One final concrete question: What is your recommended/testing setting for the umask, cacheFileMode and user account/group?

**Comment by lisachenko** [comment]
Hi, @i3anaan! Framework respects your umask configuration (if you set it previously for the security reason and prevent web server to write files), so probably your need to change it for your php environment.

What is your current umask mask?

Also, you could change `cacheFileMode` to your value. Bu default, `cacheFileMode` equals to the `0770 & ~umask()` in order to respect your setting.

**Comment by i3anaan** [comment]
Hey!
A quick response, awesome!
Our umask in the app/ folder is set to `0022`
I have tried many settings for cacheFileMode from `000`, `0770`, `777`, but it seemed to produce some weird result. Honestly I am considering some number storage format issue that is messing up the actual bitmask of the associated number.

**Comment by i3anaan** [comment]
I do want to note that going into the docker container itself, as root, commands such as `composer update` are able to generate the files and folders. (However, our system is apparently not running as root).

What this tells me is that it is for sure a permission issue.

**Comment by i3anaan** [comment]
Additionally what is confusing me is to exactly analyse where it is going wrong:

- Is the Laravel extension of Go! experiencing a bug?
- Is the base Go! framework experiencing a bug?
- Is the bug located in the doctrine/annotations library?
- Are we simply having a user issue?

Could you perhaps provide me with the exact code point where the bitmask is passed to the doctrine library? I tried to find this myself in order to see what is being passed, but due to being unknown to the codebases was not able to find it.

**Comment by lisachenko** [comment]
From you reports I can see that directory was created with wrong privileges. I'm passing correct umask to the `FileCacheReader` constructor in the `GoAspectContainer.php`, line 99

```php
                $reader = new FileCacheReader(
                    $reader,
                    $options['cacheDir'] . DIRECTORY_SEPARATOR . '_annotations' . DIRECTORY_SEPARATOR,
                    $options['debug'],
                    0777 & (~$options['cacheFileMode'])
                );
```

So, if you use `0777` as `cacheFileMode` then umask parameter will be 0000 and later, in the FileCacheReader constructor `mkdir` will be called with mode `0777 & (~0) = 0777` and directory should be writeable.

However, if your umask is set to the `0022` then `mkdir($dirName, 0777, true)` will create directory with `0777 & (~0022) = 0755` permissions. This means that group and others won't be able to write anything into this directory.

You could change your umask setting to the `0002` to allow writing for the group and add your sever into this group.

**Comment by i3anaan** [comment]
Will try this first thing tomorrow, thanks!

**Comment by i3anaan** [comment]
Hey, just tried it and got some other result:
`dr----x--t 2 laradock laradock 4096 Jul 13 10:24 aspect`

Actually having a umask of 0000 in storage/app/ and a `cacheFileMode` of 0777 gives me the following:
`dr----x--t 2 laradock laradock 4096 Jul 13 10:28 aspect`

(Expecting full rights)

**Comment by i3anaan** [comment]
Did some further testing, using the location in the code you specified:

```
//umask 0000, cacheFileMode '0777'

dump($options['cacheFileMode']); //777
dump(~$options['cacheFileMode']); //-778
dump(0777 & (~$options['cacheFileMode'])); //246

// -r-------T 1 root     root     2443 Jul 13 10:44 _transformation.cache
```
The dumped values seem to somewhat make sense to me, the actual result however no.


Aside from this, I was able to resolve the errors, manually correcting permission, running the system again, correcting permissions, running system, etc.. Eventually I got to the point where the errors stopped, however now AOP does not seem to get triggered. Will look into this now.

EDIT: Still not working, no idea why/how we got actual API responses just now, changed a few lines and it is back to creating unusable files in `/storage/app/aspect/_annotations`

**Comment by i3anaan** [comment]
Hey @lisachenko 
Were you able to check/verify the above code + results?
Is there anything else I can do that could help me/you debugging this issue?

**Comment by i3anaan** [comment]
So found the issue:
I wrote `cacheFileMode` as a string, not a number.

You might want to add that to the documentation, or my advice: Put a `0` instead of a `null` as a standard to give a hint for it (it depends a bit on how you are using it I guess).

**Comment by IamBusy** [comment]
hey, @i3anaan 
I came across the same problem. However when I set `cacheFileMode` to `0777`, the problem was solved. You can try it.

**Comment by i3anaan** [comment]
Hey @IamBusy Thank you for the suggestion!, this was the same solution I came up with.
(I had `'0777'` before changing it to `0777`)

**Comment by lisachenko** [comment]
Thank you @IamBusy and @i3anaan!

Added explicit hint about integer file mode: https://github.com/goaop/goaop-laravel-bridge/commit/f515a5152ab62af8fb9531dab2314cc63ef82afb
